package:
  name: "agb"
  version: "0.5.4"

source:
  git_rev: b0c9f7b
  git_url: https://github.com/almiheenko/AGB

build:
  number: 0

requirements:
  host:
    - python
    - setuptools

  build:
    - python
    - six
    - cython
    - minimap2
    - nxmetis
    - quast >=5.0

  run:
    - python
    - networkx <=2.3
    - six
    - cython
    - gfapy
    - minimap2
    - nxmetis
    - quast >=5.0

test:
  import:
    - nxmetis

about:
  home: https://github.com/almiheenko/AGB
  license: GPLv2
  license_file: ../LICENSE
